vrrp_script chk_mariadb {
    script "killall -0 mariadbd"
    interval 2
    weight -20
}

vrrp_instance VI_1 {
    state BACKUP
    interface ens3
    virtual_router_id 51
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass 1111
    }
    virtual_ipaddress {
        192.168.100.200
    }
    track_script {
        chk_mariadb
    }
}
